services:
  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - "./mongodb-data:/data/db"
  rabbitmq:
    image: rabbitmq:3.10.0-management
    ports: 
      - 5672:5672
      - "15672:15672"